version: "3.8"
services:
  mysql_service:
    image: mysql:8.0
    hostname: mysql_service
    container_name: mysql_service
    restart: always
    volumes:
      - /developer/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 2s
      retries: 10
  redis_db_service:
    image: redis
    hostname: redis_db_service
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    container_name: redis_db_service
  timescaledb:
    image: timescale/pg_prometheus:latest-pg10
    container_name: timescaledb
    volumes:
      - /developer/postgresql_data:/var/lib/postgresql/data:z
      - /developer/db_backups:/db_backups:z
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      TIMESCALEDB_TELEMETRY: "off"
      POSTGRES_PASSWORD: "postgres"
    hostname: timescaledb
    shm_size: "8gb"
