version: "3.8"

services:
  mysql_service:
    image: mysql:8.0
    hostname: mysql_service
    container_name: mysql_service
    restart: always
    volumes:
      - /developer/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_DEFAULT}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 2s
      retries: 10

  redis_db_service:
    image: redis
    hostname: redis_db_service
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    expose:
      - 6379
    container_name: redis_db_service

  timescaledb:
    hostname: timescaledb
    # image: timescale/pg_prometheus:latest-pg10
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /developer/postgresql_data:/var/lib/postgresql/data:z
      - /developer/db_backups:/db_backups:z
    # ports:
    #   - 5432:5432/tcp
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_DB}
      - DB_HOST=timescale
      - DB_NAME=${POSTGRES_DB}
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres
    ports:
      - "5432:5432"
    depends_on:
      - timescaledb

  grafana:
    hostname: grafana
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    hostname: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus:ro

  prom_mysql_exporter:
    image: prom/mysqld-exporter
    restart: always
    links:
      - mysql_service
      - prometheus
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: root:${MYSQL_ROOT_PASSWORD}@(mysql_service:3306)/

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    restart: always
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:${POSTGRES_PASSWORD}@timescaledb:5432/?sslmode=disable"
    links:
      - timescaledb
      - prometheus

volumes:
  grafana_data: {}
  prometheus-data:
